### ISSUE TITLE
[BUG] NullPointerException

### ISSUE THREAD

**Issue by TysonTheEmber** [ErdbeerbaerLP/DiscordIntegration-Core#183]
**What happened?**
-Whenever a msg is sent a NullPointerException error occurs

**What should happen?**
-Messages sent without error

**Steps to reproduce**
- Install and setup
- Enable webhooks

**Version**
-
Minecraft 1.20.1
Mod/plugin: latest

**Platform**
-
- [ *] Forge
- [ ] Spigot

**Config file**
-https://hastebin.com/share/ubowuwulus.ini
*REMOVE YOUR BOT TOKEN BEFORE UPLOADING!!!*

**Crash report if available (use https://hastebin.com)**
-

**Additional info**
-messages still are sent and recieved

**Comment by TysonTheEmber** [comment]
[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Member.getEffectiveName()" because the return value of "net.dv8tion.jda.api.events.message.MessageReceivedEvent.getMember()" is null
        at TRANSFORMER/dcintegration@3.0.5/de.erdbeerbaerlp.dcintegration.common.DiscordEventListener.onEvent(DiscordEventListener.java:109)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:177)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:138)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1015)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:901)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:879)
        at TRANSFORMER/dcintegration@3.0.5/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1054)
        at TRANSFORMER/dcintegration@3.0.5/dcshadow.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
        at TRANSFORMER/dcintegration@3.0.5/dcshadow.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
        at TRANSFORMER/dcintegration@3.0.5/dcshadow.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
        at TRANSFORMER/dcintegration@3.0.5/dcshadow.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
        at TRANSFORMER/dcintegration@3.0.5/dcshadow.com.neovisionaries.ws.client.ReadingThread.main(Rea

**Comment by ErdbeerbaerLP** [comment]
Should be fixed already, closing

**Comment by TysonTheEmber** [comment]
Very much NOT fixed.
![image](https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/assets/101071342/4d733dc9-5bbf-459a-b74d-390411032632)
